### PR TITLE
rebuilld the webhook using nodejs

### LINKED ISSUE #1: Rebuild with nodejs
@chichundan

### PR DESCRIPTION
**Pull request by wuyuncheng-26**
resolve #1

### CODE REVIEW

**Comment by shankkyy** [comment]
is it now working fine ?and a gentle reminder to close the issue

**Comment by wuyuncheng-26** [comment]
> is it now working fine ?and a gentle reminder to close the issue

idk but i think it's ok

**Comment by wuyuncheng-26** [comment]
嗯？？？

**Comment by JingHai-Lingyun** [comment]
I think that is no problem, let me check it

**Pull request merged**
